### ISSUE TITLE
[$50 bounty] Automatic Phone Sync with iOS Screen Time API

### ISSUE THREAD

**Issue by abdurraheemali** [ActivityWatch/aw-import-screentime#10]
**Note: Definitely more than $50 of work; hoping others can chime in to make this not an _insultingly_ bad offer.**

## Screen time API

Introduced in iOS15, based on the [WWDC21 Session](https://developer.apple.com/videos/play/wwdc2021/10123/), seems to be more of a parental control thing. 

Checking out the [API docs](https://developer.apple.com/documentation/screentimeapidocumentation/) takes me to the[DeviceActivity](Ihttps://developer.apple.com/documentation/DeviceActivity) framework. Within that there's a [DeviceActivityReport](https://developer.apple.com/documentation/deviceactivity/deviceactivityreport) for iOS16+, with the following caveat:

> sandbox prevents your extension from making network requests or moving sensitive content outside the extension’s address space

I checked Apple's [Support forum](https://discussions.apple.com/thread/254928860) and they recommended https://timingapp.com, but that didn't seem to be what I was looking for. There might be a workaround if the laptop and phone are connected via bluetooth, or maybe via iCloud, but I'm not sure what they'd be. I looked for usage on Github to see if something like this already exists but that doesn't seem to be the case.

I'm not sure if there's a way to do this without making a TestFlight app. There could be a hack from manually taking screenshots with ScreenCaptureKit and uploading that for an OCR, but that feels inelegant, and I'd probably forget to do it. Maybe Calendar and EventKit?

## Use case

Mainly want this to back up screen time history longer than the current retention dates.

**Comment by abdurraheemali** [comment]
## Previous discussions:

https://stackoverflow.com/questions/76378861/is-it-possible-through-screen-time-api-to-get-the-iphone-usage-time-raw-data-fo/76387736#76387736
https://forum.activitywatch.net/t/ios-application/1357
https://forum.activitywatch.net/t/watcher-for-ios-chrome-browsing-history/984
https://forum.activitywatch.net/t/ios-support-and-using-the-vpn-feature-to-do-so/1244

## Earlier Response

> Unfortunately not. The new API does not let other applications retrieve the usage data, only manage restrictions.

> Apple was very blatant in the announcement video for the API that “there is no way for anyone outside of your family, or even Apple, to know which websites you’ve visited, or which apps you’ve used”:

**Comment by abdurraheemali** [comment]
Closing for now as there's no clear path forward.

**Comment by MrJarnould** [comment]
@abdurraheemali I figured out a fix, see https://github.com/ActivityWatch/aw-import-screentime/pull/12 . Please donate the $50 to a charity.
